# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

In [3]:
import sys

In [4]:
sys.version

'3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]'

# Data Preprocessing

# Importing Dataset

In [5]:
df = pd.read_csv(r'C:\Users\Hp\Churn_Modelling.csv')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


# Numerical Variables in the dataset

In [7]:
df.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

# Categorical Variables in the dataset

In [8]:
colname=[]

for x in df.columns:
    if df[x].dtype==object:
        colname.append(x)
colname

['Surname', 'Geography', 'Gender']

In [9]:
df['Surname'].value_counts()

Smith     32
Martin    29
Scott     29
Walker    28
Brown     26
          ..
Nworie     1
Mouzon     1
Jacka      1
Grover     1
Kable      1
Name: Surname, Length: 2932, dtype: int64

In [10]:
df['Geography'].value_counts()   

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [11]:
df['Gender'].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

# Encoding categorical variables

Since the geography has more than 2 classes in its column so we perform one hot encoding but we can perform Label Encoding on Gender column, since the Surname doesn't contribute to our model we can ignore that column.

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France       0   42   
1          2    15647311      Hill          608     Spain       0   41   
2          3    15619304      Onio          502    France       0   42   
3          4    15701354      Boni          699    France       0   39   
4          5    15737888  Mitchell          850     Spain       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [13]:
from sklearn.preprocessing import OneHotEncoder
enc= OneHotEncoder(handle_unknown='ignore')
enc_df = pd.DataFrame(enc.fit_transform(df[['Geography']]).toarray())
df = df.join(enc_df)
df.head()    #France: 1 0 0, Germany : 0 1 0 ,Spain : 0 0 1


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France       0   42   
1          2    15647311      Hill          608     Spain       0   41   
2          3    15619304      Onio          502    France       0   42   
3          4    15701354      Boni          699    France       0   39   
4          5    15737888  Mitchell          850     Spain       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited    0    1    2  
0        101348.88       1  1.0  0.0  0.0  
1        112542.58       0  0.0  0.0  1.0  
2        113931.57       1  1.0  0.0  0.0  
3         93826.63       0  1.0  0.0  0.0  
4         79084.10       0  0.0  0.0  1.0

In [14]:
df.columns

Index([      'RowNumber',      'CustomerId',         'Surname',
           'CreditScore',       'Geography',          'Gender',
                   'Age',          'Tenure',         'Balance',
         'NumOfProducts',       'HasCrCard',  'IsActiveMember',
       'EstimatedSalary',          'Exited',                 0,
                       1,                 2],
      dtype='object')

In [15]:
column_names = [ 'RowNumber',      'CustomerId',         'Surname',
           'CreditScore',       'Geography',          'Gender',
                   'Age',          'Tenure',         'Balance',
         'NumOfProducts',       'HasCrCard',  'IsActiveMember',
       'EstimatedSalary',                           0,
                       1,                 2, 'Exited']

In [16]:
df = df.reindex(columns = column_names)

In [17]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France       0   42   
1          2    15647311      Hill          608     Spain       0   41   
2          3    15619304      Onio          502    France       0   42   
3          4    15701354      Boni          699    France       0   39   
4          5    15737888  Mitchell          850     Spain       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary    0    1    2  Exited  
0        101348.88  1.0  0.0  0.0       1  
1        112542.58  0.0  0.0  1.0       0  
2        113931.57  1.0  0.0  0.0       1  
3         93826.63  1.0  0.0  0.0       0  
4         79084.10  0.0  0.0  1.0       0

In [18]:
df1 = pd.DataFrame(df)

In [19]:
df1.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France       0   42   
1          2    15647311      Hill          608     Spain       0   41   
2          3    15619304      Onio          502    France       0   42   
3          4    15701354      Boni          699    France       0   39   
4          5    15737888  Mitchell          850     Spain       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary    0    1    2  Exited  
0        101348.88  1.0  0.0  0.0       1  
1        112542.58  0.0  0.0  1.0       0  
2        113931.57  1.0  0.0  0.0       1  
3         93826.63  1.0  0.0  0.0       0  
4         79084.10  0.0  0.0  1.0       0

In [20]:
def drop_var(name):
    df.drop(name, axis = 1, inplace = True )

In [21]:
drop_var('Geography')

In [22]:
drop_var('RowNumber')

In [23]:
drop_var('CustomerId')

In [24]:
drop_var('Surname')

In [25]:
df.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary    0    1    2  Exited  
0               1        101348.88  1.0  0.0  0.0       1  
1               1        112542.58  0.0  0.0  1.0       0  
2               0        113931.57  1.0  0.0  0.0       1  
3               0         93826.63  1.0  0.0  0.0       0  
4               1         79084.10  0.0  0.0  1.0       0

# Splitting X and Y

In [26]:
X = df.values[:,:-1]
Y = df.values[:,-1]

In [27]:
X

array([[619.,   0.,  42., ...,   1.,   0.,   0.],
       [608.,   0.,  41., ...,   0.,   0.,   1.],
       [502.,   0.,  42., ...,   1.,   0.,   0.],
       ...,
       [709.,   0.,  36., ...,   1.,   0.,   0.],
       [772.,   1.,  42., ...,   0.,   1.,   0.],
       [792.,   0.,  28., ...,   1.,   0.,   0.]])

In [28]:
Y

array([1., 0., 1., ..., 1., 1., 0.])

# Train Test Split

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state = 101)

# Feature Scaling

In [30]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Building ANN

# Initializing ANN

In [31]:
ann = tf.keras.models.Sequential()

# Adding the input layer and first hidden layer

In [32]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the input layer and first hidden layer

In [33]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the output layer

In [34]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Part 3 - Training the ANN

# Compiling the ANN

In [35]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Training the ANN on the Training set

In [36]:
ann.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
219/219 [==============================] - 0s 1ms/step - loss: 0.6246 - accuracy: 0.6681
Epoch 2/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4642 - accuracy: 0.8047
Epoch 3/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4409 - accuracy: 0.8131
Epoch 4/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4301 - accuracy: 0.8190
Epoch 5/100
219/219 [==============================] - ETA: 0s - loss: 0.4266 - accuracy: 0.81 - 0s 2ms/step - loss: 0.4222 - accuracy: 0.8206
Epoch 6/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4145 - accuracy: 0.8254
Epoch 7/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4073 - accuracy: 0.8280
Epoch 8/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4007 - accuracy: 0.8334
Epoch 9/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3952 - accuracy: 0.8339
Epoch 10/100
219/219 [===========================

Epoch 81/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3345 - accuracy: 0.8624
Epoch 82/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3338 - accuracy: 0.8646
Epoch 83/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3339 - accuracy: 0.8633
Epoch 84/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3344 - accuracy: 0.8613
Epoch 85/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3338 - accuracy: 0.8629
Epoch 86/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3338 - accuracy: 0.8647
Epoch 87/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3337 - accuracy: 0.8636
Epoch 88/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3341 - accuracy: 0.8631
Epoch 89/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3333 - accuracy: 0.8624
Epoch 90/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3332

# Part 4 - Making the predictions and evaluating the model

# Predicting the result of a single observation

In [37]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))) #Probability of cust. leaving the bank

[[0.]]


In [38]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5) #Customer's final outcome 

[[False]]


# Predicting Test Results

In [39]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0. 0.]
 [0. 0.]
 [0. 1.]
 ...
 [0. 0.]
 [1. 0.]
 [1. 1.]]


In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)
accuracy_score(Y_test, y_pred)

[[2267  111]
 [ 293  329]]


0.8653333333333333